apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: akash63/portfolio-v2:new
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort