name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        description: select environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod