#Deploy
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push Docker image with branch-based tag
        run: |
          TAG=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          IMAGE=${{ secrets.DOCKER_USERNAME }}/demo-portfolio:$TAG
          docker build -t $IMAGE .
          docker push $IMAGE
